name: cellprofiler

channels:
- conda-forge
- anaconda
- bioconda
- defaults

dependencies:
- python=3.8
- pip
- numpy=1.23.0
- matplotlib
- pandas
- mysqlclient
- openjdk
- scikit-learn
- mahotas
- python-javabridge
- Jinja2=3.0.1
- inflect=5.3.0
- wxPython
- mysqlclient=1.4.4
- sentry-sdk=0.18.0
- ipykernel
- pip:
    - cellprofiler==4.2.6
    - cellpose==2.2.2
    - cellpose[gui]
    - csbdeep
    - stardist